apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: hetzner-object-storage-kog
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/hetzner-object-storage-kog
    version: "0.1.0"
