apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hetzner-object-storage-kog.fullname" . }}-bucket-oas
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hetzner-object-storage-kog.labels" . | nindent 4 }}
data:
  hetzner-object-storage.yaml: |-
{{ .Files.Get "files/hetzner-object-storage.yaml" | indent 4 }}
