apiVersion: v1
kind: Secret
metadata:
  name: hetzner-s3-credentials
  namespace: default
type: Opaque
stringData:
  username: REPLACE_WITH_HETZNER_S3_ACCESS_KEY
  password: REPLACE_WITH_HETZNER_S3_SECRET_KEY
